server:
  port: 8081

spring:
  application:
    name: "Customer service"
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: "boski"
    password: "boskipw"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop