server:
  port: 8082

spring:
  application:
    name: "Fraud service"
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: "boski"
    password: "boskipw"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update